version: "1"

networks:
  gitea:
    external: false

services:
  server:
    image: asciiteaparty:v1_gitea1-19-0
    container_name: AsciiTeaParty
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      # - ./gitea-docker-data:/data
      - ./custom/app.ini:/data/gitea/conf/app.ini
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
